services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: comp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
        context: ./api
        dockerfile: Dockerfile
    environment:
      DJANGO_DEBUG: "1"
      CORS_ALLOW_ALL: "1"        
    env_file: .env
    depends_on:
        - postgres
    ports:
    - "9070:8000"   # host:container
    volumes:
        - ./api:/app
    command: >
        bash -lc "
        python manage.py migrate &&
        python manage.py loaddata initial_data || true &&
        gunicorn comp_api.wsgi:application -c gunicorn.conf.py
        "

volumes:
  pgdata: {}
