name: CI
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ feature/** ]

jobs:
  api:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: api } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: pip install -r requirements.txt
      - name: Lint & Tests
        run: |
          pytest -q || true  # replace with real tests when ready

  ai:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: ai } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: pip install -r requirements.txt
      - name: Lint & Tests
        run: echo "TODO: add tests"

  web:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: web } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install & Build
        run: |
          npm ci
          npm run build
